### ISSUE TITLE
Customer Feedback

### ISSUE THREAD

**Issue by zinniadesignsTC** [denniswhitney2000/ZinniaCeramics#11]
These are for Etsy: 
-Love these little dishes! So far I've purchased 3! One for a graduation gift, another for a wedding gift and a birthday gift! 
-This was beyond amazing and she catered to my specific very personalized needs and helped me create a great gift for a sister.
-Adorable dish and so much better than others because of the customization! Makes me smile every time I see it.

This are for "Imprints": 
-The work you did is gorgeous! I'm so thrilled with the way everything came out. We will enjoy them for years to come.
-Thank you so much, they are so precious and beautiful! To be cherished forever by these dads! 
-Thank you so much for the beautiful, beautiful tiles you made. My mother-in-law cried when she saw hers! I truly feel like these are just priceless.

**Comment by denniswhitney2000** [comment]
This is in place and will be deployed in a few minutes.
