### ISSUE TITLE
Hands and Foot pics

### ISSUE THREAD

**Issue by zinniadesignsTC** [denniswhitney2000/ZinniaCeramics#12]
I tried to get pics of ones that are close to my logo colors. 
![img_3894](https://cloud.githubusercontent.com/assets/20828528/17537549/8b151bd8-5e6b-11e6-8fed-6c274b5f2074.jpg)
![img_3896](https://cloud.githubusercontent.com/assets/20828528/17537550/8b1bc190-5e6b-11e6-892f-b37e169178d8.jpg)
![img_3897](https://cloud.githubusercontent.com/assets/20828528/17537552/8b1cafc4-5e6b-11e6-8204-c73eeaff6ef3.jpg)
![img_3898](https://cloud.githubusercontent.com/assets/20828528/17537551/8b1c2c48-5e6b-11e6-95c0-0fee40c0e094.jpg)

**Comment by denniswhitney2000** [comment]
Thank you!
I will be replacing the hands and feet in the site to use these
