### ISSUE TITLE
Text for About 

### ISSUE THREAD

**Issue by zinniadesignsTC** [denniswhitney2000/ZinniaCeramics#13]
About (add in color picture of my work) 

Zinnia Designs Custom Ceramics by Tanya Chin 

I capture a moment in time by creating a handmade tile or dish with impressions of your little one’s hands and feet in clay. I can also help you celebrate an engagement, wedding, anniversary, birthday, baptism, confirmation or holiday with my personalized ceramic dishes, plaques & ornaments. 

In 1998 I graduated from Mass Art with a BFA in ceramics. Then I spent many years as a marketing manager and eventually started creating with clay again. In 2009 after the birth of our son I decided to say goodbye to corporate and focus on family and Zinnia Designs custom ceramics. In 2012 our daughter’s arrival competed our little family. My studio is located in our home allowing me to have a nice family/career balance. Days can be long and very busy, but I wouldn’t trade it for the world! 

Visit the “shop” link above to see all the custom personalized items I offer in my Etsy shop. Additional information on hand & foot impressions is found under “imprints”. I personally hand make each piece and impress the images/text into the clay so no 2 pieces are ever exactly the same. I take great pride in creating beautiful items you will treasure forever and in providing great customer service to all. I look forward to working with you to create a personalized keepsake!

**Comment by denniswhitney2000** [comment]
Done!
