### ISSUE TITLE
Text for Services- Imprints

### ISSUE THREAD

**Issue by zinniadesignsTC** [denniswhitney2000/ZinniaCeramics#14]
Services- change to “Imprints"

Your tiny baby will be off to school before you know it. Capture a moment in time by having me create a personalized, decorative piece with impressions of your little one’s hands & feet in clay. All ages are welcome from infant (4 weeks+) to adult. These precious pieces make wonderful gifts for mom, dad, grandparents & God parents. 

Email or call to make your weekday or Saturday appointment. The day of your appointment come to my bright and cheery studio and we’ll pick the colors, designs and personalized details for your tile together. I’ll neatly take the impressions in non-toxic clay and then I do the rest of the work in my studio. The piece will be complete in approximately 4+ weeks depending on my production schedule. 

Pricing:
1 tile with 1 impression = $50
1 tile with 2 impressions = $70
1 tile with 3-4 impressions = $110
Above prices includes colored border and imprints, standard name and age/date text, stamped designs and simple 3D designs. Detailed 3D designs are an additional $10. Family tree additional $20.

Host a “Clay Date” and I’ll come to you!
Host your mommy friends for a fun and creative event at your home. I will come ready to neatly take everyone’s impressions in the comfort of your own home. Moms can mingle and the kids can play while I individually meet to discuss the decorative details for your tile and quickly take the impressions. Contact me for more information about hosting your own “clay date”.

**Comment by denniswhitney2000** [comment]
Done, with edits.
