### ISSUE TITLE
Text for Etsy- Shop

### ISSUE THREAD

**Issue by zinniadesignsTC** [denniswhitney2000/ZinniaCeramics#15]
Etsy Shop- change to “Shop”

New Text for above the Etsy pic:  Zinnia Designs handmade, high quality custom ceramics make the perfect gift. A truly personal keepsake to be treasured for ever! To see more use arrow or double click to go to Etsy. Some items are ready to ship and I also love doing very custom/personalized orders, so please contact me with your ideas.

**Comment by denniswhitney2000** [comment]
Done and deployed.
