### ISSUE TITLE
Font ?

### ISSUE THREAD

**Issue by zinniadesignsTC** [denniswhitney2000/ZinniaCeramics#16]
Hi Dennis- so I was thinking we should use the same font as my business card. I have no clue what that font is, but I have attached a file here so maybe you can open it and see. Its a PDF so I'm assuming not, but let me know. If not I can contact the designer. Thanks! 
[zinnia_front_426B.pdf](https://github.com/denniswhitney2000/ZinniaCeramics/files/424052/zinnia_front_426B.pdf)

**Comment by denniswhitney2000** [comment]
Hey! Digging into this now and so far, so bad....
