### ISSUE TITLE
About section

### ISSUE THREAD

**Issue by zinniadesignsTC** [denniswhitney2000/ZinniaCeramics#17]
1. I think we can remove the "ABOUT" text seeing that when someone is in that section it's highlighted in the nav bar. 
2. The last sentence "I look forward to working with you to create a personalized keepsake!" change the "a" to "your" 
3. Remove the ornament photo
4. Replace the hand and foot with the aqua or aqua/green hands/feet so it matches better

**Comment by denniswhitney2000** [comment]
For #1, while yes we can, it is generally considered good design to label the individual page sections.
If you really want it gone, no problem, but still...

For the others, no problem.

**Comment by zinniadesignsTC** [comment]
ya I say we nix the labels on the sections. If the sections were bigger I can see the need, but they are short and we have them broken up with the page colors.
