### ISSUE TITLE
Shop section

### ISSUE THREAD

**Issue by zinniadesignsTC** [denniswhitney2000/ZinniaCeramics#19]
1. Again I think we can get rid of "SHOP"
2. The customer quotes are doubled up- I think you already have a ticket on this, but figured I'd just mention it. 
3. Can you change the price on the picture to be the green from my page instead of bright blue? 
4. Text change: In my Etsy shop you will find handmade, high quality ceramic keepsakes. Fully customizable with personalization, fun designs & bright colors make my pieces unique. You'll find many ready to ship and custom made items to choose from, but new ideas are always welcomed. 
5. Below the pic remove this text "Some items are ready to ship and I also love doing very custom/personalized orders, so please contact me with your ideas."

**Comment by denniswhitney2000** [comment]
This is done and I fixed the etsy slider so that you can see all of your items
