### ISSUE TITLE
Contact us

### ISSUE THREAD

**Issue by denniswhitney2000** [denniswhitney2000/ZinniaCeramics#7]
Confirm text and layout

**Comment by denniswhitney2000** [comment]
Also. add the social media icons and links

**Comment by denniswhitney2000** [comment]
Instagram: http://instagram.com/zinniadesigns?ref=badge
Twitter: https://twitter.com/zinniadesigns
Flickr: http://www.flickr.com/photos/zinniadesigns/
Etsy: https://www.etsy.com/shop/zinniadesignstc?ref=em
Facebook: http://www.facebook.com/zinniadesigns
**DONE**

**Comment by denniswhitney2000** [comment]
Update the email address to info@zinia-designs.com
**DONE**

**Comment by zinniadesignsTC** [comment]
Change the phone # to 781-690-5619. If you could do dots instead of dashes that would match my biz card- thanks!

**Comment by denniswhitney2000** [comment]
Done.
