### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by zinniadesignsTC** [denniswhitney2000/ZinniaCeramics#9]
![zinniadesignslogoblk](https://cloud.githubusercontent.com/assets/20828528/17387627/69d09f9e-59c3-11e6-95e5-4246166125dd.jpg)

I can't upload the eps file that I have so if you want it let me know and I'll email it to you.

**Comment by denniswhitney2000** [comment]
Hey!
This should be fine and will be in place in the next deployment.
